# Generated by Django 6.0.5 on 2026-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_delete_postt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
